#! /bin/bash

set -ex

# Make a link from the shared documents directory to the user home directory.
ln -s ~/shared/docs ~/docs

# Make a local cache directory.
mkdir -p ~/cache
# Link some global cache directories to the user's local cache.
ln -s ~/shared/cache/PNC_FreeSurfer ~/cache/PNC_FreeSurfer

# Install pixi.
curl -fsSL https://pixi.sh/install.sh | PIXI_VERSION=v0.72.1 bash
